apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-deployment
  labels:
    app: predictor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: zhukovmsu/otus-hw:1889b8d42d668cb3c64c3d6c6422807c4da886a6
        ports:
        - containerPort: 8890