apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predictor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: predictor
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: predictor-service
            port:
              number: 80