apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: predictor
spec:
  endpoints:

  - path: /metrics
    port: predictor
    scheme: http
    interval: 10s

  jobLabel: predictor
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: predictor