apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: predictor
  namespace: predictor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: predictor
  minReplicas: 4
  maxReplicas: 6