# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
#          pip install -e .
      - name: Unit tests with pytest
        run: |
          pip install pytest-cov
          pytest tests

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Checkout repository
#      run: ls -la
#    - name: Build Docker image
#      run: docker build -t ${{ env.IMAGE_NAME }} .
#    - name: Login to Docker Hub
#      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#      with:
#        username: ${{ env.DOCKER_HUB_USER }}
#        password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
#    - name: Push image to Docker Hub
#      run: docker push ${{ env.IMAGE_NAME }}
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - name: Deploy to server
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ env.SERVER_HOST }}
#        username: ${{ env.SERVER_USER }}
#        key: ${{ env.SERVER_SSH_PRIVATE_KEY }}
#        script: |
#          docker pull ${{ env.IMAGE_NAME }}
#          docker stop ${{ env.CONTAINER_NAME }} || true
#          docker rm ${{ env.CONTAINER_NAME }} || true
#          docker run -d -p 8890:8890 --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME }}